export const transactionActionTypes = {
  LOAD_USER_TRANSACTIONS_START: "LOAD_USER_TRANSACTIONS_START",
  LOAD_USER_TRANSACTIONS_SUCCESS: "LOAD_USER_TRANSACTIONS_SUCCESS",
  LOAD_USER_TRANSACTIONS_FAILURE: "LOAD_USER_TRANSACTIONS_FAILURE",
};
